# Generated by Django 4.1.3 on 2022-11-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dockets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.CharField(max_length=100)),
                ('docket_number', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('book_page', models.CharField(blank=True, max_length=100)),
                ('docket_entry', models.CharField(blank=True, max_length=100)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficialSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clerks_File_No', models.CharField(max_length=255)),
                ('Doc_Type', models.CharField(blank=True, max_length=255)),
                ('Rec_Date', models.DateField()),
                ('Rec_Book_or_Page', models.CharField(max_length=255)),
                ('Plat_Book_or_Page', models.CharField(max_length=255)),
                ('Blk', models.CharField(blank=True, max_length=255)),
                ('Legal', models.CharField(blank=True, max_length=255)),
                ('Misc_Ref', models.CharField(blank=True, max_length=255)),
                ('First_Party_Code', models.CharField(blank=True, max_length=255)),
                ('Second_Party_Code', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Parties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_description', models.CharField(blank=True, max_length=255)),
                ('party_name', models.CharField(max_length=100)),
                ('attorney_information', models.CharField(blank=True, max_length=100)),
                ('attorney_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_case_number', models.CharField(max_length=100)),
                ('docket', models.ManyToManyField(to='base.dockets')),
                ('parties', models.ManyToManyField(to='base.parties')),
            ],
        ),
    ]
