# Generated by Django 4.1.3 on 2022-11-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='docket',
            new_name='dockets',
        ),
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='state_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
