# Generated by Django 4.1.3 on 2022-11-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_docket_case_dockets_case_case_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parties',
            name='local_case_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
